# Generated by Django 4.2.5 on 2023-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_restaurant_delete_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
