# Generated by Django 4.2.5 on 2023-11-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_restaurant_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
