# Generated by Django 5.0.2 on 2024-02-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_openinghour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghour',
            options={'ordering': ('day', '-from_hour')},
        ),
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('restaurant', 'day', 'from_hour', 'to_hour')},
        ),
    ]
