# Generated by Django 5.0.2 on 2024-04-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0009_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
