# Generated by Django 5.0.2 on 2024-04-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_reviewandrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Restaurant.restaurant'),
        ),
    ]
