# Generated by Django 5.0.2 on 2024-03-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_state_alter_order_tax_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('PayPal', 'PayPal')], max_length=100),
        ),
    ]
