# Generated by Django 5.0.2 on 2024-04-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_restaurants_order_total_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti')], max_length=100),
        ),
    ]
